---
title: "practical_exercise_8 , Methods 3, 2021, autumn semester"
author: "Mina Almasi, Daniel Blumenkranz, Anton Drasbæk Schiønning, Matilde Sterup"
date: "24/11/21"
output: pdf_document
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>


# Exercises and objectives

1) Load the magnetoencephalographic recordings and do some initial plots to understand the data  
2) Do logistic regression to classify pairs of PAS-ratings  
3) Do a Support Vector Machine Classification on all four PAS-ratings  

REMEMBER: In your report, make sure to include code that can reproduce the answers requested in the exercises below (__MAKE A KNITTED VERSION__)  
REMEMBER: This is Assignment 3 and will be part of your final portfolio   

# EXERCISE 1 - Load the magnetoencephalographic recordings and do some initial plots to understand the data  

The files `megmag_data.npy` and `pas_vector.npy` can be downloaded here (http://laumollerandersen.org/data_methods_3/megmag_data.npy) and here (http://laumollerandersen.org/data_methods_3/pas_vector.npy)   

```{r}
library(reticulate)
```


```{python}
import numpy as np 
import os 
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
```


```{python}
os.chdir("/Users/minaalmasi/Documents/Cognitive_Science/Methods_3/methods3_code/data_W8")
```


#### 1) Load `megmag_data.npy` and call it `data` using `np.load`. You can use `join`, which can be imported from `os.path`, to create paths from different string segments
```{python}
data = np.load("megmag_data.npy")
```

##### i. The data is a 3-dimensional array. The first dimension is number of repetitions of a visual stimulus , the second dimension is the number of sensors that record magnetic fields (in Tesla) that stem from neurons activating in the brain, and the third dimension is the number of time samples. How many repetitions, sensors and time samples are there?  
```{python}
data.shape # prints (number of repetitions, number sensors, number of time samples)

print(data)
```

There are 682 repetitions, 102 number of sensors and 251 number of time samples. 

##### ii. The time range is from (and including) -200 ms to (and including) 800 ms with a sample recorded every 4 ms. At time 0, the visual stimulus was briefly presented. Create a 1-dimensional array called `times` that represents this.  

```{python}
times = np.arange(-200, 804, 4)
```

##### iii. Create the sensor covariance matrix $\Sigma_{XX}$: $$\Sigma_{XX} = \frac 1 N \sum_{i=1}^N XX^T$$ $N$ is the number of repetitions and $X$ has $s$ rows and $t$ columns (sensors and time), thus the shape is $X_{s\times t}$. Do the sensors pick up independent signals? (Use `plt.imshow` to plot the sensor covariance matrix)  
```{python}
N = len(data)

X = data[0,:,:]

cov_temp = np.zeros(shape = (102, 102))

for i in range(N):
  X = data[i,:,:]
  X_T = np.transpose(X)
  cov_temp += np.dot(X, X_T)

cov = cov_temp / N

plt.figure()
plt.imshow(cov)
plt.title("1.1iii: Sensor Covariance Matrix")
plt.show()
```

The sensors seem to pick up different signals for the most part, since the covariance matrix plot of the sensors has a petrol/navy color in general, which corresponds to a covariance of about 0. The yellow color at around 50 however indicates high covariance. 


##### iv. Make an average over the repetition dimension using `np.mean` - use the `axis` argument. (The resulting array should have two dimensions with sensors as the first and time as the second)  
```{python}
mean_teslas = np.mean(data, axis = 0) #axis = 0 indicates the first dimension (repetitions)

mean_teslas.shape
```

##### v. Plot the magnetic field (based on the average) as it evolves over time for each of the sensors (a line for each) (time on the x-axis and magnetic field on the y-axis). Add a horizontal line at $y = 0$ and a vertical line at $x = 0$ using `plt.axvline` and `plt.axhline`  
```{python}
plt.figure()
plt.plot(times, mean_teslas.T)
plt.axvline(color = "black")
plt.axhline(color = "black")
plt.title("The Average of the Magnetic Field Across Repetitions")
plt.xlabel("Time (ms)")
plt.ylabel("Magnetic Field (Tesla)")
plt.show()
```

##### vi. Find the maximal magnetic field in the average. Then use `np.argmax` and `np.unravel_index` to find the sensor that has the maximal magnetic field.  
```{python}
# MAXIMIMAL MAGNETIC FIELD AVG. #
np.max(mean_teslas)

# SENSOR WITH THE MAXIMAL MAGNETIC FIELD # 
np.unravel_index(np.argmax(mean_teslas), mean_teslas.shape)

times[112] # time in ms 
```

The maximal magnetic field in the average is 2.7886216843591933e-13. 

With np.unravel_index and np.argmax we get the sensor with the maximal magnetic field to be 73 as given by the coordinate system (73, 112). In the calculation, the time is given in the time-samples, but by printing this index from the times vector, we get the time in ms of 248. This number fits the peak of the red sensor in the plot from 1.1v. 

##### vii. Plot the magnetic field for each of the repetitions (a line for each) for the sensor that has the maximal magnetic field. Highlight the time point with the maximal magnetic field in the average (as found in 1.1.v) using `plt.axvline`  
```{python}
## SAVING SENSOR 73 ## 
sensor73 = data[:,73,:]

## PLOTTING SENSOR 73 ##
plt.figure()
plt.plot(times, sensor73.T)
plt.axvline(times[112], color = "black", linestyle = "--")
plt.axvline(color = "black")
plt.axhline(color = "black")

time_point_max = mpatches.Patch(color='black', label='time at avg maximal magnetic field', linestyle = "--")

plt.legend(handles=[time_point_max])

plt.title("Average Magnetic Field Across Repetitions")
plt.xlabel("Time (ms)")
plt.ylabel("Magnetic Field (Tesla)")

plt.show()
```

**ATTENCIONE** fix plot legend

##### viii. Describe in your own words how the response found in the average is represented in the single repetitions. But do make sure to use the concepts _signal_ and _noise_ and comment on any differences on the range of values on the y-axis  

**ATTENCIONE ** write later

#### 2) Now load `pas_vector.npy` (call it `y`). PAS is the same as in Assignment 2, describing the clarity of the subjective experience the subject reported after seeing the briefly presented stimulus  
```{python}
y = np.load("pas_vector.npy")
```

    
##### i. Which dimension in the `data` array does it have the same length as?  
```{python}
# CHECKING the length of y #
len(y)

# The dimension it has the same length as #
len(y) == len(data[:,0,0])

```

y has the same length as the first dimension *repetitions* in our data array. 

##### ii. Now make four averages (As in Exercise 1.1.iii), one for each PAS rating, and plot the four time courses (one for each PAS rating) for the sensor found in Exercise 1.1.v  
```{python}
### FINDING the indexes of the pas ratings 
pas1 = np.where(y == 1)
pas2 = np.where(y == 2)
pas3 = np.where(y == 3)
pas4 = np.where(y == 4)

### FINDING the mean TESLA values for each pas rating for all time values 
mean_pas1 = np.mean(sensor73[pas1], axis = 0)
mean_pas1.shape

mean_pas2 = np.mean(sensor73[pas2], axis = 0)
mean_pas2.shape

mean_pas3 = np.mean(sensor73[pas3], axis = 0)
mean_pas3.shape

mean_pas4 = np.mean(sensor73[pas4], axis = 0)
mean_pas4.shape 

## PLOTTING the mean TESLA values for sensor 73 for each pas rating 
plt.figure()
plt.plot(times, mean_pas1.T, color = "blue")
plt.plot(times, mean_pas2.T, color = "green")
plt.plot(times, mean_pas3.T, color = "orange")
plt.plot(times, mean_pas4.T, color = "red")
plt.axvline(color = "black")
plt.axhline(color = "black")

Pas1 = mpatches.Patch(color='blue', label='pas1')
Pas2 = mpatches.Patch(color='green', label='pas2')
Pas3 = mpatches.Patch(color='orange', label='pas3')
Pas4 = mpatches.Patch(color='red', label='pas4')

plt.legend(handles=[Pas1, Pas2, Pas3, Pas4])


plt.title("Average Magnetic Field Across Repetitions for Sensor 73")
plt.xlabel("Time (ms)")
plt.ylabel("Magnetic Field (Tesla)")

plt.show()
```


##### iii. Notice that there are two early peaks (measuring visual activity from the brain), one before 200 ms and one around 250 ms. Describe how the amplitudes of responses are related to the four PAS-scores. Does PAS 2 behave differently than expected?  

To recap, the perceptual awareness scale has 4 categorically different ratings: 

1. No Experience (NE)
2. Weak Glimpse (WG)
3. Almost Clear Experience (ACE)
4. Clear Experience (CE)

Firstly, the curve for pas 1 fits the theoretical expectations that having no experience should result in the least amount of activity (measured through magnetic field in this case). Following this logic, we would expect each pas rating to gradually increase in activation. 

However, pas3 and pas4 is very similar in activation which is not surprising considering the rather opaque difference in their definitions.  

Unexpectedly, pas2 has the highest peak which goes against the theoretical reasoning.

# EXERCISE 2 - Do logistic regression to classify pairs of PAS-ratings  

#### 1) Now, we are going to do Logistic Regression with the aim of classifying the PAS-rating given by the subject

##### i. We'll start with a binary problem - create a new array called `data_1_2` that only contains PAS responses 1 and 2. Similarly, create a `y_1_2` for the target vector 
```{python}
pas1_2 = np.where((y==1)|(y==2))
data_1_2=data[pas1_2]

data_1_2.shape #checking that we did it right

#Target vector
y_1_2 = y[(y==1)|(y==2)] 
y_1_2
```

ii. Scikit-learn expects our observations (`data_1_2`) to be in a 2d-array, which has samples (repetitions) on dimension 1 and features (predictor variables) on dimension 2. Our `data_1_2` is a three-dimensional array. Our strategy will be to collapse our two last dimensions (sensors and time) into one dimension, while keeping the first dimension as it is (repetitions). Use `np.reshape` to create a variable `X_1_2` that fulfils these criteria. 
```{python}
#Reshaping
X_1_2 = data_1_2.reshape(data_1_2.shape[0],-1) 

#data_1_2.shape[0] is repetitions with pas 1 or pas 2. This is the dimension we want to keep.
# -1 collapses the second and third dimension. This is sensors and time. 
#https://panjeh.medium.com/convert-numpy-3d-array-to-2d-array-in-python-931a4cdf8b12

X_1_2.shape
X_1_2
```

```{python}
print(data_1_2)
```

##### iii. Import the `StandardScaler` and scale `X_1_2` 
```{python}
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()


X_1_2_scaled = scaler.fit_transform(X_1_2)
X_1_2_scaled.shape
```



##### iv. Do a standard `LogisticRegression` - can be imported from `sklearn.linear_model` - make sure there is no `penalty` applied  
```{python}
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(penalty='none')

lr.fit(X_1_2_scaled,y_1_2)
```

##### v. Use the `score` method of `LogisticRegression` to find out how many labels were classified correctly. Are we overfitting? Besides the score, what would make you suspect that we are overfitting?  
```{python}
lr.score(X_1_2_scaled, y_1_2)
```
If we interpret this correctly, our logistic regression correctly classifies 100 % of the labels, which makes us suspect that something is wrong. We believe we are overfitting, because the accuracy is very high. We have not split the data into test and training sets, so the model "knows" the correct classifications, as it has been trained on the very data it is asked to predict.

##### vi. Now apply the _L1_ penalty instead - how many of the coefficients (`.coef_`) are non-zero after this?  

```{python}
lr = LogisticRegression(penalty='l1', solver ='liblinear', random_state=1)
lr.fit(X_1_2_scaled,y_1_2)
lr.coef_.shape
lr.score(X_1_2_scaled, y_1_2)

np.count_nonzero(lr.coef_) #counting the non-zero coefficients
```

##### vii. Create a new reduced $X$ that only includes the non-zero coefficients - show the covariance of the non-zero features (two covariance matrices can be made; $X_{reduced}X_{reduced}^T$ or $X_{reduced}^TX_{reduced}$ (you choose the right one)) . Plot the covariance of the features using `plt.imshow`. Compared to the plot from 1.1.iii, do we see less covariance? 
```{python}
###REDUCED X###
non_zero = np.where(lr.coef_ != 0)
print(non_zero) # We only need the information in the second column
print(non_zero[1])

reduced_X = X_1_2_scaled[:,non_zero[1]] # Taking the previous X_1_2_scaled and subsetting the non-zero coefficients

reduced_X.shape

###COVARIANCE OF NON-ZERO FEATURES###

#We would like to end up with a 282 by 282 matrix. When we multiply two matrices, we get the first matrix' rows and the second matrix' columns. We choose the formula, where the rows of the transposed matrix (282) is multiplied with the columns of the matrix (282) - features x features

reduced_X_cov = reduced_X.T@reduced_X
reduced_X_cov.shape #hurra

###Plotting the covariance###
plt.figure()
plt.imshow(reduced_X_cov)
plt.title("2.1vii: Non-Zero Coefficients Covariance Matrix")
plt.colorbar()
plt.show()

#1.1iii
plt.figure()
plt.imshow(cov)
plt.title("1.1iii: Sensor Covariance Matrix")
plt.colorbar()
plt.show()
```

These plots are not easily comparable (0 correspond to a different shade across plots, and the scale is different). *ATTENCIONE* We will ask Lau about this. Our new plot is 'lighter' which could mean more covariance.


#### 2) Now, we are going to build better (more predictive) models by using cross-validation as an outcome measure    


#### i. Import `cross_val_score` and `StratifiedKFold` from `sklearn.model_selection`  
```{python}
from sklearn.model_selection import cross_val_score, StratifiedKFold
```


##### ii. To make sure that our training data sets are not biased to one target (PAS) or the other, create `y_1_2_equal`, which should have an equal number of each target. Create a similar `X_1_2_equal`. The function `equalize_targets_binary` in the code chunk associated with Exercise 2.2.ii can be used. Remember to scale `X_1_2_equal`!  
```{python}
# Exercise 2.2.ii
def equalize_targets_binary(data, y):
    np.random.seed(7)
    targets = np.unique(y) ## find the number of targets
    if len(targets) > 2:
        raise NameError("can't have more than two targets")
    counts = list()
    indices = list()
    for target in targets:
        counts.append(np.sum(y == target)) ## find the number of each target
        indices.append(np.where(y == target)[0]) ## find their indices
    min_count = np.min(counts)
    # randomly choose trials
    first_choice = np.random.choice(indices[0], size=min_count, replace=False)
    second_choice = np.random.choice(indices[1], size=min_count,replace=False)
    
    # create the new data sets
    new_indices = np.concatenate((first_choice, second_choice))
    new_y = y[new_indices]
    new_data = data[new_indices, :, :]
    
    return new_data, new_y
```

```{python}
## USING THE FUNCTION ##
data_1_2_equal, y_1_2_equal = equalize_targets_binary(data_1_2, y_1_2)

### investigating y_1_2_equal ###
y_1_2_equal.shape
np.where(y_1_2_equal == 1)
np.where(y_1_2_equal == 2) 
# we see that there are 99 of each

### investigating data_1_2_equal ###
data_1_2_equal.shape

# Reshaping
X_1_2_equal = data_1_2_equal.reshape(X_1_2_equal.shape[0],-1) 
X_1_2_equal.shape

# Scaling
scaler = StandardScaler()
X_1_2_equal_scaled = scaler.fit_transform(X_1_2_equal)
X_1_2_equal_scaled.shape
```

By running X_1_2 equal_scaled.shape, we see that we have now 198 pas ratings (corresponding to 99 pas1 and 99 pas2 ratings) and the 25602 coefficients. 

##### iii. Do cross-validation with 5 stratified folds doing standard `LogisticRegression` (See Exercise 2.1.iv)  
```{python}
## fitting the model ##
log = LogisticRegression(penalty='none')

log.fit(X_1_2_equal_scaled, y_1_2_equal)

## cross validation ## 
cv = StratifiedKFold(n_splits=5) #defining that we want 5 folds 

scores_log = cross_val_score(log, X_1_2_equal_scaled, y_1_2_equal, cv=cv)
print(np.mean(scores_log))
```

Our model is barely above chance level (0.535) when you take the mean of the prediction accuracy from the 5 cv fits. 

##### iv. Do L2-regularisation with the following `Cs=  [1e5, 1e1, 1e-5]`. Use the same kind of cross-validation as in Exercise 2.2.iii. In the best-scoring of these models, how many more/fewer predictions are correct (on average)? 

```{python}
## L2-Regularisation & Cross-Validation Calculations ## 

#Log 1e5 
log_1e5 = LogisticRegression(penalty='l2', C=1e5)
log_1e5.fit(X_1_2_equal_scaled, y_1_2_equal)

scores_log_1e5 = cross_val_score(log_1e5, X_1_2_equal_scaled, y_1_2_equal, cv=cv)

#Log 1e1
log_1e1 = LogisticRegression(penalty='l2', C=1e1)
log_1e1.fit(X_1_2_equal_scaled, y_1_2_equal)

scores_log_1e1 = cross_val_score(log_1e1, X_1_2_equal_scaled, y_1_2_equal, cv=cv)

#Log 1e-5
log_1e_neg5 = LogisticRegression(penalty='l2', C=1e-5) 

log_1e_neg5.fit(X_1_2_equal_scaled, y_1_2_equal)

scores_log_1e_neg5 = cross_val_score(log_1e_neg5, X_1_2_equal_scaled, y_1_2_equal, cv=cv)
```


```{python}
## Cross-validation Score ## 
print("Cross-Validation Score w. C = 1e5:", np.mean(scores_log_1e5).round(3))
print("Cross-Validation Score w. C = 1e1:", np.mean(scores_log_1e1).round(3))
print("Cross-Validation Score w. C = 1e-5:", np.mean(scores_log_1e_neg5).round(3))
```

The model with the lowest C ($C = 1e-5$) has the highest accuracy (0.596) meaning that introducing penalty improves prediction accuracy. We can count the amount of predictions that are correct and compare with the model with no penalty made in iii:

```{python}
## Amount of predictions correct ## 
from sklearn.model_selection import cross_val_predict

## Accuracy Log 1e-5
predict_log1e_neg5 = cross_val_predict(log_1e_neg5, X_1_2_equal_scaled, y_1_2_equal, cv=cv)
accuracy_log1e_neg5 = predict_log1e_neg5 == y_1_2_equal

## Accuracy Log Model 2.2iii
predict_log = cross_val_predict(log, X_1_2_equal_scaled, y_1_2_equal, cv=cv)
accuracy_log = predict_log == y_1_2_equal

print("Correct Predictions Log 2.2iii:", len(np.where(accuracy_log == True)[0]))
print("Correct Predictions Log 1e-5:", len(np.where(accuracy_log1e_neg5 == True)[0]))
```

The amount of predictions that are correct with the penalized model (log 1e-5) are 118 whereas the non-penalised model only has 106. 

##### v. Instead of fitting a model on all `n_sensors * n_samples` features, fit  a logistic regression (same kind as in Exercise 2.2.iv (use the `C` that resulted in the best prediction)) for __each__ time sample and use the same cross-validation as in Exercise 2.2.iii. What are the time points where classification is best? Make a plot with time on the x-axis and classification score on the y-axis with a horizontal line at the chance level (what is the chance level for this analysis?)  

```{python}



```

    
##### vi. Now do the same, but with L1 regression - set `C=1e-1` - what are the time points when classification is best? (make a plot)?  


vii. Finally, fit the same models as in Exercise 2.2.vi but now for `data_1_4` and `y_1_4` (create a data set and a target vector that only contains PAS responses 1 and 4). What are the time points when classification is best? Make a plot with time on the x-axis and classification score on the y-axis with a horizontal line at the chance level (what is the chance level for this analysis?)  



3) Is pairwise classification of subjective experience possible? Any surprises in the classification accuracies, i.e. how does the classification score fore PAS 1 vs 4 compare to the classification score for PAS 1 vs 2?  


```{python, eval=FALSE}
# Exercise 2.2.ii
def equalize_targets_binary(data, y):
    np.random.seed(7)
    targets = np.unique(y) ## find the number of targets
    if len(targets) > 2:
        raise NameError("can't have more than two targets")
    counts = list()
    indices = list()
    for target in targets:
        counts.append(np.sum(y == target)) ## find the number of each target
        indices.append(np.where(y == target)[0]) ## find their indices
    min_count = np.min(counts)
    # randomly choose trials
    first_choice = np.random.choice(indices[0], size=min_count, replace=False)
    second_choice = np.random.choice(indices[1], size=min_count,replace=False)
    
    # create the new data sets
    new_indices = np.concatenate((first_choice, second_choice))
    new_y = y[new_indices]
    new_data = data[new_indices, :, :]
    
    return new_data, new_y
```

# EXERCISE 3 - Do a Support Vector Machine Classification on all four PAS-ratings  
1) Do a Support Vector Machine Classification  
    i. First equalize the number of targets using the function associated with each PAS-rating using the function associated with Exercise 3.1.i  
    ii. Run two classifiers, one with a linear kernel and one with a radial basis (other options should be left at their defaults) - the number of features is the number of sensors multiplied the number of samples. Which one is better predicting the category?
    iii. Run the sample-by-sample analysis (similar to Exercise 2.2.v) with the best kernel (from Exercise 3.1.ii). Make a plot with time on the x-axis and classification score on the y-axis with a horizontal line at the chance level (what is the chance level for this analysis?)
    iv. Is classification of subjective experience possible at around 200-250 ms?  
2) Finally, split the equalized data set (with all four ratings) into a training part and test part, where the test part if 30 % of the trials. Use `train_test_split` from `sklearn.model_selection`  
    i. Use the kernel that resulted in the best classification in Exercise 3.1.ii and `fit`the training set and `predict` on the test set. This time your features are the number of sensors multiplied by the number of samples.  
    ii. Create a _confusion matrix_. It is a 4x4 matrix. The row names and the column names are the PAS-scores. There will thus be 16 entries. The PAS1xPAS1 entry will be the number of actual PAS1, $y_{pas1}$ that were predicted as PAS1, $\hat y_{pas1}$. The PAS1xPAS2 entry will be the number of actual PAS1, $y_{pas1}$ that were predicted as PAS2, $\hat y_{pas2}$ and so on for the remaining 14 entries.  Plot the matrix
    iii. Based on the confusion matrix, describe how ratings are misclassified and if that makes sense given that ratings should measure the strength/quality of the subjective experience. Is the classifier biased towards specific ratings?  
    
```{python, eval=FALSE}

def equalize_targets(data, y):
    np.random.seed(7)
    targets = np.unique(y)
    counts = list()
    indices = list()
    for target in targets:
        counts.append(np.sum(y == target))
        indices.append(np.where(y == target)[0])
    min_count = np.min(counts)
    first_choice = np.random.choice(indices[0], size=min_count, replace=False)
    second_choice = np.random.choice(indices[1], size=min_count, replace=False)
    third_choice = np.random.choice(indices[2], size=min_count, replace=False)
    fourth_choice = np.random.choice(indices[3], size=min_count, replace=False)
    
    new_indices = np.concatenate((first_choice, second_choice,
                                 third_choice, fourth_choice))
    new_y = y[new_indices]
    new_data = data[new_indices, :, :]
    
    return new_data, new_y

```